@baseURL=http://housingmovie-env.eba-syvga2mw.ap-southeast-1.elasticbeanstalk.com/api

# CRUD Genre

# @name GetGenre
GET {{baseURL}}/genres

###

# @name PostGenre
POST {{baseURL}}/genre
content-type: application/json

{
    "name": "Adult"
}

###
# @name DeleteGenre
DELETE {{baseURL}}/genre
content-type: application/json

{
    "id":"c708ef8f-f93b-437b-ba56-87e2ca435903"
}

###

