@baseURL=https://api.themoviedb.org/3
@apiKey=54aa709695ac2db22242917da035c1fa
@movie_id=9c6562e9-498d-4c3f-a786-2150052afd3a

# Discover Movies

# @name GetDiscoverMovie
GET {{baseURL}}/discover/movie?api_key={{apiKey}}&page=6

###
# @name SearchMovie
GET {{baseURL}}/search/movie?api_key={{apiKey}}&query= 

###

# Movie Detail

# @name GetMovieDetail
GET {{baseURL}}/movie/{{movie_id}}?api_key={{apiKey}}

###

# @name Genre
GET {{baseURL}}/genre/movie/list?api_key={{apiKey}}